# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.1 04d03e8"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "spore"
template_type = "Rust"

[[contracts]]
name = "cluster"
template_type = "Rust"

[[contracts]]
name = "cluster_proxy"
template_type = "Rust"

[[contracts]]
name = "cluster_agent"
template_type = "Rust"
