# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.2 5e49142"
# path of deployment config file
deployment = "deployment.toml"

# CAUTION: contracts order cannot be changed here

[[contracts]]
name = "spore_extension_lua"
template_type = "Rust"

[[contracts]]
name = "cluster"
template_type = "Rust"

[[contracts]]
name = "cluster_proxy"
template_type = "Rust"

[[contracts]]
name = "cluster_agent"
template_type = "Rust"

[[contracts]]
name = "spore"
template_type = "Rust"
