[workspace]
members = ["contracts/cellular", "contracts/always-success", "lib/types", "lib/utils", "contracts/cellular-series"]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
