[workspace]
members = [
    "lib/types",
    "lib/utils",
    "lib/errors",

    "contracts/spore",
    "contracts/cluster",
    "contracts/cluster_proxy",
    "contracts/cluster_agent",
    "contracts/spore_extension_lua",
]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
