[package]
name = "cluster_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.14.0"
spore-utils = { path = "../../lib/utils" }
spore-constant = { path = "../../lib/constant"}